### ISSUE TITLE
keyla-0.1.9-x64 would not start under win7-64

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Ryzhehvost/keyla#28]
```

1. Install keyla-0.1.9-x64-setup.exe
2. Run keyla.exe 
Application immediately crushes with 0xc000007b

keyla-0.1.9-x64, Win7 Pro 64 bit


```

Original issue reported on code.google.com by `smishc...@gmail.com` on 9 Jan 2013 at 2:24

Attachments:
* [1.PNG](https://storage.googleapis.com/google-code-attachments/keyla/issue-28/comment-0/1.PNG)

**Comment by Ryzhehvost** [comment]
duplicate of #26
